metadata:
  version: 0.0
  sys_prompt: "There are several options:"
  gpt_eval_model_name: "gpt-3.5-turbo-1106"
group: mtcbench_image
task: "mmbench_en_test_mtcbench"
test_split: test
include: _default_template_mmbench_en_yaml
metric_list:
  - metric: gpt_eval_score
    aggregation: !function utils.mmbench_aggregate_dev_results_eval_en
    higher_is_better: true
  - metric: submission
    aggregation: !function utils.mmbench_aggregate_test_results_en
    higher_is_better: true