dataset_path: /root/data2/lisida/MTC-Bench-Data/image/General_Multimodal_Capbility/MMBench
dataset_name: cc
dataset_kwargs:
  token: True
  local_files_only: True
  verification_mode: "no_checks"
task: "mmbench_cn_cc_mtcbench"
test_split: test
output_type: generate_until
group: mtcbench_image
doc_to_visual: !function utils.mmbench_doc_to_visual
doc_to_text: !function utils.mmbench_cn_cc_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 256
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.mmbench_cn_cc_process_results
metric_list:
  - metric: gpt_eval_score
    aggregation: !function utils.mmbench_cn_cc_aggregate_dev_results_eval
    higher_is_better: true
  - metric: submission
    aggregation: !function utils.mmbench_cn_cc_aggregate_results
metadata:
  version: 0.0
  gpt_eval_model_name: "gpt-3.5-turbo"

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\n请直接使用所提供的选项字母作为答案回答。"
model_specific_generation_kwargs:
  llava:
    image_aspect_ratio: original