dataset_path: /root/data2/lisida/MTC-Bench-Data/video/General_Multimodal_Capbility/NExTQA
dataset_kwargs:
  token: True
  local_files_only: True
  verification_mode: "no_checks"
  split: "test"
metadata:
  version: 0.0.1
  load_package: True
task: "nextqa_mc_test_mtcbench"
dataset_name: MC
test_split: test
group: mtcbench_video
output_type: generate_until
doc_to_visual: !function utils.nextqa_doc_to_visual
doc_to_text: !function utils.nextqa_doc_to_text_mc
doc_to_target: !function utils.nextqa_doc_to_target
process_results: !function utils.nextqa_mc_process_results
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
