dataset_path: /root/TCBench/image/Specific_Capabilities/Holistic_Vision_Coverage/CapsBench/
dataset_kwargs:
  token: True
  local_files_only: True
  ignore_verifications: True
  cache_dir: capsbench
metadata:
  version: 0.0.1
  load_package: True
task: "capsbench_test_tcbench"
test_split: test
group: tcbench_dev
output_type: generate_until

doc_to_visual: !function utils.capsbench_doc_to_visual
doc_to_text: !function utils.capsbench_doc_to_text
doc_to_target: "gpt-4o"

process_results: !function utils.capsbench_process_results

metric_list:
  - metric: BLEU_4
    aggregation: !function utils.capsbench_aggregate_results_BLEU
    higher_is_better: true
  - metric: CIDEr
    aggregation: !function utils.capsbench_aggregate_results_CIDEr
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    caption_metric: "BLEU_4"   # or "CIDEr" for the other metric run
    pre_prompt: ""
    post_prompt: "\nWrite a concise caption describing the image."
