metadata:
  version: 0.0.1
  load_package: True

dataset_path: /root/TCBench/image/Specific_Capabilities/High_rate_Compression/HR-Bench/
dataset_kwargs:
  token: True
  local_files_only: True
  ignore_verifications: True
  cache_dir: hr_bench
  data_files:
    test: "test-00000-of-00001.parquet"

task: "hr_bench_test_tcbench"
test_split: test
group: tcbench_image
output_type: generate_until

doc_to_visual: !function utils.hrbench_doc_to_visual
doc_to_text: !function utils.hrbench_doc_to_text
doc_to_target: !function utils.hrbench_doc_to_target
process_results: !function utils.hrbench_process_results

metric_list:
  - metric: exact_match
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the correct label or short phrase."
