dataset_path: /root/TCBench/video/Specific_Capabilities/Fine_grained_Vision_Coverage/MotionBench
dataset_kwargs:
  token: True
  local_files_only: True
  ignore_verifications: True
  cache_dir: motionbench
metadata:
  version: 0.0.1
  load_package: True
task: "motionbench_test_tcbench"
dataset_name: MotionBench
test_split: test
group: tcbench
output_type: generate_until

doc_to_visual: !function utils.motionbench_doc_to_visual
doc_to_text: !function utils.motionbench_doc_to_text
doc_to_target: !function utils.motionbench_doc_to_target

process_results: !function utils.generic_process_results

metric_list:
  - metric: ACCURACY
    aggregation: !function utils.accuracy_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the correct choice (single word or short phrase)."
